"""Update ContactLead

Revision ID: 291eb7a395ed
Revises: 594518857350
Create Date: 2026-07-16 16:25:07.450046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291eb7a395ed'
down_revision: Union[str, Sequence[str], None] = '594518857350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_leads', sa.Column('organisation_id', sa.UUID(), nullable=False))
    op.alter_column('contact_leads', 'research_run_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_contact_leads_organisation_id'), 'contact_leads', ['organisation_id'], unique=False)
    op.create_foreign_key(None, 'contact_leads', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact_leads', type_='foreignkey')
    op.drop_index(op.f('ix_contact_leads_organisation_id'), table_name='contact_leads')
    op.alter_column('contact_leads', 'research_run_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('contact_leads', 'organisation_id')
    # ### end Alembic commands ###
