"""Add latest_email_draft to ContactLead

Revision ID: 45922f4342e7
Revises: 41c71c4da1e0
Create Date: 2026-07-30 14:26:14.853661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45922f4342e7'
down_revision: Union[str, Sequence[str], None] = '41c71c4da1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_leads', sa.Column('latest_email_draft', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_leads', 'latest_email_draft')
    # ### end Alembic commands ###
