"""initial schema

Revision ID: 4de10fd0c82c
Revises: 
Create Date: 2026-07-16 14:18:07.683244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4de10fd0c82c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('website', sa.String(length=1000), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_name'), 'organisations', ['name'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'researching', 'extracting', 'scoring', 'completed', 'failed', name='researchstatus'), nullable=False),
    sa.Column('research_model', sa.String(length=100), nullable=False),
    sa.Column('extraction_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('discovery_text', sa.Text(), nullable=True),
    sa.Column('raw_discovery_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_organisation_id'), 'research_runs', ['organisation_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('servicenow_confidence', sa.Integer(), nullable=False),
    sa.Column('basic_use_likelihood', sa.Integer(), nullable=False),
    sa.Column('cost_pressure', sa.Integer(), nullable=False),
    sa.Column('renewal_proximity', sa.Integer(), nullable=False),
    sa.Column('migration_fit', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('servicenow_status', sa.String(length=50), nullable=False),
    sa.Column('apparent_use_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('advanced_use_cases_found', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opportunity_hypothesis', sa.Text(), nullable=False),
    sa.Column('unknowns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_stakeholders', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discovery_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_outreach', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Enum('pending', 'accepted', 'rejected', 'more_research', name='reviewstatus'), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('scoring_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_run_id')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('nature', sa.Enum('fact', 'inference', 'unknown', name='evidencenature'), nullable=False),
    sa.Column('strength', sa.Enum('strong', 'moderate', 'weak', name='evidencestrength'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=3000), nullable=True),
    sa.Column('source_title', sa.String(length=1000), nullable=True),
    sa.Column('supporting_excerpt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_research_run_id'), 'evidence_items', ['research_run_id'], unique=False)
    op.create_table('research_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=3000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('domain', sa.String(length=300), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_run_id', 'url', name='uq_research_run_source_url')
    )
    op.create_index(op.f('ix_research_sources_research_run_id'), 'research_sources', ['research_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_sources_research_run_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_evidence_items_research_run_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_research_runs_organisation_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_organisations_name'), table_name='organisations')
    op.drop_table('organisations')
    # ### end Alembic commands ###
