"""Add contact leads table

Revision ID: 594518857350
Revises: 4de10fd0c82c
Create Date: 2026-07-16 15:37:57.773293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594518857350'
down_revision: Union[str, Sequence[str], None] = '4de10fd0c82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('job_title', sa.String(length=300), nullable=False),
    sa.Column('linkedin_url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=3000), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_leads_research_run_id'), 'contact_leads', ['research_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_leads_research_run_id'), table_name='contact_leads')
    op.drop_table('contact_leads')
    # ### end Alembic commands ###
