"""add email to contact_leads

Revision ID: 7f89eac1f2a3
Revises: a1f6a3585b94
Create Date: 2026-07-31 11:57:58.736835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f89eac1f2a3'
down_revision: Union[str, Sequence[str], None] = 'a1f6a3585b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_leads', sa.Column('email', sa.String(length=300), nullable=True))
    op.add_column('contact_leads', sa.Column('email_is_guessed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_leads', 'email_is_guessed')
    op.drop_column('contact_leads', 'email')
    # ### end Alembic commands ###
