"""Add latest_linkedin_draft to ContactLead

Revision ID: 8d9b886f952f
Revises: 7f89eac1f2a3
Create Date: 2026-08-12 12:57:49.009875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9b886f952f'
down_revision: Union[str, Sequence[str], None] = '7f89eac1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_leads', sa.Column('latest_linkedin_draft', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_leads', 'latest_linkedin_draft')
    # ### end Alembic commands ###
