"""Rename servicenow_ to itsm_ and add identified_tools

Revision ID: a1f6a3585b94
Revises: 45922f4342e7
Create Date: 2026-07-30 22:47:28.456870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f6a3585b94'
down_revision: Union[str, Sequence[str], None] = '45922f4342e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'servicenow_confidence', new_column_name='itsm_confidence')
    op.alter_column('assessments', 'servicenow_status', new_column_name='itsm_status')
    op.add_column('assessments', sa.Column('identified_tools', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'identified_tools')
    op.alter_column('assessments', 'itsm_status', new_column_name='servicenow_status')
    op.alter_column('assessments', 'itsm_confidence', new_column_name='servicenow_confidence')
    # ### end Alembic commands ###
