"""Add PromptConfig

Revision ID: b509af2d5989
Revises: 291eb7a395ed
Create Date: 2026-07-16 16:43:07.335767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b509af2d5989'
down_revision: Union[str, Sequence[str], None] = '291eb7a395ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_configs',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.add_column('assessments', sa.Column('pursuit_gate', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'pursuit_gate')
    op.drop_table('prompt_configs')
    # ### end Alembic commands ###
