"""add current_message to research_run

Revision ID: c0d4d88161b0
Revises: b509af2d5989
Create Date: 2026-07-23 08:17:08.837471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d4d88161b0'
down_revision: Union[str, Sequence[str], None] = 'b509af2d5989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_runs', sa.Column('current_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_runs', 'current_message')
    # ### end Alembic commands ###
