"""add prospecting run

Revision ID: c18217fe5e26
Revises: c0d4d88161b0
Create Date: 2026-07-29 14:46:22.078826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18217fe5e26'
down_revision: Union[str, Sequence[str], None] = 'c0d4d88161b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospecting_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='prospectingstatus'), nullable=False),
    sa.Column('current_message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prospecting_runs')
    # ### end Alembic commands ###
