"""Add status to ContactLead

Revision ID: cdd5d76770d5
Revises: 8d9b886f952f
Create Date: 2026-08-12 13:30:52.789982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd5d76770d5'
down_revision: Union[str, Sequence[str], None] = '8d9b886f952f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    contact_status_enum = sa.Enum('discovered', 'researched', 'emailed', 'replied', name='contactstatus')
    contact_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('contact_leads', sa.Column('status', contact_status_enum, server_default='discovered', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_leads', 'status')
    op.execute("DROP TYPE contactstatus")
    # ### end Alembic commands ###
